M48
; DRILL file {KiCad 7.0.10-7.0.10~ubuntu22.04.1} date Wed 10 Jul 2024 07:59:33 PM EDT
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-07-10T19:59:33-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.10-7.0.10~ubuntu22.04.1
; #@! TF.FileFunction,NonPlated,1,8,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1260
%
G90
G05
T1
X2.275Y-1.5
X2.275Y-4.05
X4.45Y-1.5
X4.45Y-4.05
M30
